/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutAuthImport } from './routes/_layout/_auth'
import { Route as LayoutAuthNotificationsImport } from './routes/_layout/_auth/notifications'
import { Route as LayoutAuthAdminsImport } from './routes/_layout/_auth/_admins'
import { Route as LayoutAuthAdminsCreateAdminImport } from './routes/_layout/_auth/_admins/createAdmin'
import { Route as LayoutAuthAdminsAdminListImport } from './routes/_layout/_auth/_admins/adminList'
import { Route as LayoutAuthAdminsEditAdminUserIdImport } from './routes/_layout/_auth/_admins/editAdmin/$userId'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const CustomerLoginLazyImport = createFileRoute('/customer/login')()
const LayoutTradingTradingListLazyImport = createFileRoute(
  '/_layout/_trading/tradingList',
)()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const CustomerLoginLazyRoute = CustomerLoginLazyImport.update({
  path: '/customer/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/customer/login.lazy').then((d) => d.Route),
)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTradingTradingListLazyRoute =
  LayoutTradingTradingListLazyImport.update({
    path: '/tradingList',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_trading/tradingList.lazy').then((d) => d.Route),
  )

const LayoutAuthNotificationsRoute = LayoutAuthNotificationsImport.update({
  path: '/notifications',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthAdminsRoute = LayoutAuthAdminsImport.update({
  id: '/_admins',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthAdminsCreateAdminRoute =
  LayoutAuthAdminsCreateAdminImport.update({
    path: '/createAdmin',
    getParentRoute: () => LayoutAuthAdminsRoute,
  } as any)

const LayoutAuthAdminsAdminListRoute = LayoutAuthAdminsAdminListImport.update({
  path: '/adminList',
  getParentRoute: () => LayoutAuthAdminsRoute,
} as any)

const LayoutAuthAdminsEditAdminUserIdRoute =
  LayoutAuthAdminsEditAdminUserIdImport.update({
    path: '/editAdmin/$userId',
    getParentRoute: () => LayoutAuthAdminsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/_admins': {
      id: '/_layout/_auth/_admins'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthAdminsImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/notifications': {
      id: '/_layout/_auth/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutAuthNotificationsImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_trading/tradingList': {
      id: '/_layout/_trading/tradingList'
      path: '/tradingList'
      fullPath: '/tradingList'
      preLoaderRoute: typeof LayoutTradingTradingListLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/_admins/adminList': {
      id: '/_layout/_auth/_admins/adminList'
      path: '/adminList'
      fullPath: '/adminList'
      preLoaderRoute: typeof LayoutAuthAdminsAdminListImport
      parentRoute: typeof LayoutAuthAdminsImport
    }
    '/_layout/_auth/_admins/createAdmin': {
      id: '/_layout/_auth/_admins/createAdmin'
      path: '/createAdmin'
      fullPath: '/createAdmin'
      preLoaderRoute: typeof LayoutAuthAdminsCreateAdminImport
      parentRoute: typeof LayoutAuthAdminsImport
    }
    '/_layout/_auth/_admins/editAdmin/$userId': {
      id: '/_layout/_auth/_admins/editAdmin/$userId'
      path: '/editAdmin/$userId'
      fullPath: '/editAdmin/$userId'
      preLoaderRoute: typeof LayoutAuthAdminsEditAdminUserIdImport
      parentRoute: typeof LayoutAuthAdminsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutAuthRoute: LayoutAuthRoute.addChildren({
      LayoutAuthAdminsRoute: LayoutAuthAdminsRoute.addChildren({
        LayoutAuthAdminsAdminListRoute,
        LayoutAuthAdminsCreateAdminRoute,
        LayoutAuthAdminsEditAdminUserIdRoute,
      }),
      LayoutAuthNotificationsRoute,
    }),
    LayoutIndexRoute,
    LayoutTradingTradingListLazyRoute,
  }),
  LoginLazyRoute,
  CustomerLoginLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/customer/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/",
        "/_layout/_trading/tradingList"
      ]
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/_layout/_auth": {
      "filePath": "_layout/_auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/_admins",
        "/_layout/_auth/notifications"
      ]
    },
    "/customer/login": {
      "filePath": "customer/login.lazy.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/_admins": {
      "filePath": "_layout/_auth/_admins.tsx",
      "parent": "/_layout/_auth",
      "children": [
        "/_layout/_auth/_admins/adminList",
        "/_layout/_auth/_admins/createAdmin",
        "/_layout/_auth/_admins/editAdmin/$userId"
      ]
    },
    "/_layout/_auth/notifications": {
      "filePath": "_layout/_auth/notifications.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/_trading/tradingList": {
      "filePath": "_layout/_trading/tradingList.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/_admins/adminList": {
      "filePath": "_layout/_auth/_admins/adminList.tsx",
      "parent": "/_layout/_auth/_admins"
    },
    "/_layout/_auth/_admins/createAdmin": {
      "filePath": "_layout/_auth/_admins/createAdmin.tsx",
      "parent": "/_layout/_auth/_admins"
    },
    "/_layout/_auth/_admins/editAdmin/$userId": {
      "filePath": "_layout/_auth/_admins/editAdmin/$userId.tsx",
      "parent": "/_layout/_auth/_admins"
    }
  }
}
ROUTE_MANIFEST_END */
